# Generated by Django 3.1 on 2020-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200820_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('university', 'University'), ('other', 'Other')], default='university', max_length=20),
        ),
    ]
